DROP TABLE IF EXISTS education;

CREATE TABLE education(
	education_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	degree VARCHAR(255) NOT NULL,
	time VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL
);